# Generated by Django 5.2 on 2025-12-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0003_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.quiz"
                    ),
                ),
            ],
        ),
    ]
