# Generated by Django 5.2 on 2025-12-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0005_useranswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.CharField(max_length=100),
        ),
    ]
